### ISSUE TITLE
NPM package name is wrong.

### ISSUE THREAD

**Issue by dzearing** [btd/esbuild-visualizer#1]
It should be `esbuild-visualizer` but is misspelled as `esbuld-visualizer`.

All of the documentation refers to the former. Either fix the npm package name or the docs.

**Comment by btd** [comment]
Fixed

**Comment by dzearing** [comment]
Thanks! :D

**Comment by dzearing** [comment]
@btd I still see the package.json that's in master has the wrong name:

https://github.com/btd/esbuild-visualizer/blob/9c533b5edf9b2e0189f35855c2b8af1657f17af8/package.json#L2

**Comment by dzearing** [comment]
(but I do see the package showing up in `npm show esbuild-visualizer versions`)
